name: Sync doc changes from multiple PRs

on:
  workflow_dispatch:
  push:
    paths:
      - 'sync_mult_prs.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  sync_mult_prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3

    - name: Run sync_mult_prs script
      run: |
        git config user.name "Docsite Preview Bot"
        git config user.email ""
        ./sync_mult_prs.sh
        ./.github/git_push.sh ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
