name: Sync docs on schedule

on:
  workflow_dispatch:
  schedule:
#    - cron: "0 0 */15 * *" # every 15 days
    - cron: "0 12 * * *" # every day at 20:00 (Singapore time)
#    - cron: "0 */6 * * *" # every 6 hours

# specify the preview branch for the multiple PRs
env:
  MULT_PR_PREVIEW_BRANCH: ai

jobs:
  sync_scheduler:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v5

    - name: Sync preview branch (multiple PRs) on schedule
      run: |
        gh workflow run sync_mult_prs.yml --ref ${{env.MULT_PR_PREVIEW_BRANCH}}
